version: '3'

networks:
  netw:
    driver: bridge

services:

  test_server:
    image: debian:trixie
    container_name: test_server
    networks:
    - netw
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y openssh-server &&
        echo 'root:root' | chpasswd &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config &&
        useradd -m admin &&
        echo "admin:admin" | chpasswd &&
        mkdir /var/run/sshd &&
        /usr/sbin/sshd -D 
      "

  remote_api:
    build:
      context: ./RemoteAPI
      dockerfile: Dockerfile
    container_name: remote_api
    networks:
    - netw
    ports:
    - "1414:5000"
    #depends_on:

  identity_api:
    build:
      context: ./IdentityAPI
      dockerfile: Dockerfile
    container_name: identity_api
    networks:
    - netw
    ports:
    - "1415:80"
    depends_on:
    - mssql_server

  mssql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      SA_PASSWORD: "YourPassword1!"
      #MSSQL_SA_PASSWORD: "YourPassword1!"
      ACCEPT_EULA: "Y"
    networks:
    - netw
    #ports:
    #  - "1433:1433"
