-- MySQL Script generated by MySQL Workbench
-- сб, 05-лют-2022 13:54:27 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RemoteTerminal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RemoteTerminal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RemoteTerminal` ;
USE `RemoteTerminal` ;

-- -----------------------------------------------------
-- Table `RemoteTerminal`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RemoteTerminal`.`Users` (
  `GUID` VARCHAR(64) NOT NULL,
  `Login` VARCHAR(64) NOT NULL,
  `Password` VARCHAR(128) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GUID`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RemoteTerminal`.`UserToMachine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RemoteTerminal`.`UserToMachine` (
  `GUID` VARCHAR(64) NOT NULL,
  `UserGUID` VARCHAR(64) NOT NULL,
  `MachineName` VARCHAR(45) NOT NULL,
  `Host` VARCHAR(45) NOT NULL,
  `User` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Port` INT NOT NULL,
  PRIMARY KEY (`GUID`),
  INDEX `UserToMachine_idx` (`UserGUID` ASC) VISIBLE,
  CONSTRAINT `UserToMachine`
    FOREIGN KEY (`UserGUID`)
    REFERENCES `RemoteTerminal`.`Users` (`GUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RemoteTerminal`.`HistoryToMachine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RemoteTerminal`.`HistoryToMachine` (
  `GUID` VARCHAR(64) NOT NULL,
  `MachineGUID` VARCHAR(64) NOT NULL,
  `Command` VARCHAR(128) NOT NULL,
  `Time` DATETIME NOT NULL,
  PRIMARY KEY (`GUID`),
  INDEX `HistoryToMachine_idx` (`MachineGUID` ASC) VISIBLE,
  CONSTRAINT `HistoryToMachine`
    FOREIGN KEY (`MachineGUID`)
    REFERENCES `RemoteTerminal`.`UserToMachine` (`GUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RemoteTerminal`.`CommandToUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RemoteTerminal`.`CommandToUser` (
  `GUID` VARCHAR(64) NOT NULL,
  `UserGUID` VARCHAR(64) NOT NULL,
  `Command` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GUID`),
  INDEX `CommandToUser_idx` (`UserGUID` ASC) VISIBLE,
  CONSTRAINT `CommandToUser`
    FOREIGN KEY (`UserGUID`)
    REFERENCES `RemoteTerminal`.`Users` (`GUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/*INSERT INTO Users
VALUES 
('c245c511-c076-4ee2-8df0-aa804ad5cc95', 'lol2', 'lol', 'lolname');

INSERT INTO UserToMachine
VALUES 
('96799c6d-2bcc-4826-b8ef-50f1d502b662', 'c245c511-c076-4ee2-8df0-aa804ad5cc95', 'machineName', 'host', 'username', 'password', 22);*/
